"""sync schema

Revision ID: 01eefdf82888
Revises: 277b5770c360
Create Date: 2026-01-06 23:05:15.372676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '01eefdf82888'
down_revision: Union[str, Sequence[str], None] = '277b5770c360'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tenants', 'status',
               existing_type=sa.TEXT(),
               server_default='ACTIVE',
               existing_nullable=False)
    op.alter_column('tenants', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tenants', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('tenants', 'status',
               existing_type=sa.TEXT(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###
