"""Add playlist tables

Revision ID: 5095649d46a4
Revises: 863e9867ac49
Create Date: 2026-01-12 14:02:36.190392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5095649d46a4'
down_revision: Union[str, Sequence[str], None] = '863e9867ac49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.alter_column(
        'content_versions',
        'state',
        existing_type=postgresql.ENUM(
            'DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'PUBLISHED', 'ARCHIVED',
            name='content_state'
        ),
        server_default=None,
        existing_nullable=False,
    )

    op.drop_constraint(
        op.f('content_versions_media_asset_id_version_number_key'),
        'content_versions',
        type_='unique'
    )

    # FIXED: explicit cast using USING
    op.execute("""
        ALTER TABLE media_assets 
        ALTER COLUMN size_bytes 
        TYPE BIGINT 
        USING size_bytes::bigint;
    """)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('media_assets', 'size_bytes',
               existing_type=sa.BigInteger(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_unique_constraint(op.f('content_versions_media_asset_id_version_number_key'), 'content_versions', ['media_asset_id', 'version_number'], postgresql_nulls_not_distinct=False)
    op.alter_column('content_versions', 'state',
               existing_type=postgresql.ENUM('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'PUBLISHED', 'ARCHIVED', name='content_state'),
               server_default=sa.text("'DRAFT'::content_state"),
               existing_nullable=False)
    # ### end Alembic commands ###
