"""Add playlist tables

Revision ID: c2cc27f10612
Revises: 5095649d46a4
Create Date: 2026-01-12 14:09:45.197064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c2cc27f10612'
down_revision: Union[str, Sequence[str], None] = '5095649d46a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playlist_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('playlist_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlists.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('playlist_id', 'version_number', name='uq_playlist_versions_playlist_version')
    )
    op.drop_table('schedules')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedules',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('zone_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('playlist_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('start_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('end_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlists.id'], name=op.f('schedules_playlist_id_fkey')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('schedules_tenant_id_fkey')),
    sa.ForeignKeyConstraint(['zone_id'], ['screen_zones.id'], name=op.f('schedules_zone_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('schedules_pkey'))
    )
    op.drop_table('playlist_versions')
    # ### end Alembic commands ###
