"""check media alignment

Revision ID: c8f53c1669a4
Revises: 3f556ca988e4
Create Date: 2026-01-04 21:55:08.922549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c8f53c1669a4'
down_revision: Union[str, Sequence[str], None] = '3f556ca988e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('playlist_items')
    op.drop_index(op.f('idx_heartbeat_device_time'), table_name='device_heartbeats')
    op.drop_table('device_heartbeats')
    op.drop_table('content_versions')
    op.drop_table('playlists')
    op.drop_table('screen_zones')
    op.drop_table('emergency_media')
    op.drop_table('screen_layouts')
    op.drop_table('schedules')
    op.drop_table('locations')
    op.drop_table('emergency_messages')
    op.drop_table('screens')
    op.add_column('audit_logs', sa.Column('actor', sa.Text(), nullable=False))
    op.add_column('audit_logs', sa.Column('entity', sa.Text(), nullable=False))
    op.alter_column('audit_logs', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('audit_logs', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('audit_logs', 'action',
               existing_type=postgresql.ENUM('CREATE', 'UPDATE', 'DELETE', 'APPROVE', 'REVOKE', 'LOGIN', 'EMERGENCY', name='audit_action'),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('audit_logs', 'entity_id',
               existing_type=sa.UUID(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('audit_logs', 'payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.Text(),
               nullable=True)
    op.alter_column('audit_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_audit_tenant_time'), table_name='audit_logs')
    op.drop_constraint(op.f('audit_logs_tenant_id_fkey'), 'audit_logs', type_='foreignkey')
    op.drop_column('audit_logs', 'actor_device_id')
    op.drop_column('audit_logs', 'actor_user_id')
    op.drop_column('audit_logs', 'entity_type')
    op.alter_column('media_assets', 'filename',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('media_assets', 'mime_type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('media_assets', 'checksum',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('media_assets', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_unique_constraint(None, 'media_assets', ['filename'])
    op.drop_constraint(op.f('media_assets_tenant_id_fkey'), 'media_assets', type_='foreignkey')
    op.drop_column('media_assets', 'tenant_id')
    op.alter_column('roles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('roles_tenant_id_name_key'), 'roles', type_='unique')
    op.create_unique_constraint('uq_role_name_per_tenant', 'roles', ['tenant_id', 'name'])
    op.alter_column('tenants', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('tenants', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    op.drop_constraint(op.f('users_tenant_id_email_key'), 'users', type_='unique')
    op.create_unique_constraint('uq_user_email_per_tenant', 'users', ['tenant_id', 'email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_email_per_tenant', 'users', type_='unique')
    op.create_unique_constraint(op.f('users_tenant_id_email_key'), 'users', ['tenant_id', 'email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'deleted_at',
               existing_type=sa.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('tenants', 'deleted_at',
               existing_type=sa.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('tenants', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('uq_role_name_per_tenant', 'roles', type_='unique')
    op.create_unique_constraint(op.f('roles_tenant_id_name_key'), 'roles', ['tenant_id', 'name'], postgresql_nulls_not_distinct=False)
    op.alter_column('roles', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('media_assets', sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('media_assets_tenant_id_fkey'), 'media_assets', 'tenants', ['tenant_id'], ['id'])
    op.drop_constraint(None, 'media_assets', type_='unique')
    op.alter_column('media_assets', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('media_assets', 'checksum',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('media_assets', 'mime_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('media_assets', 'filename',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.add_column('audit_logs', sa.Column('entity_type', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('audit_logs', sa.Column('actor_user_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('audit_logs', sa.Column('actor_device_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('audit_logs_tenant_id_fkey'), 'audit_logs', 'tenants', ['tenant_id'], ['id'])
    op.create_index(op.f('idx_audit_tenant_time'), 'audit_logs', ['tenant_id', sa.literal_column('created_at DESC')], unique=False)
    op.alter_column('audit_logs', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('audit_logs', 'payload',
               existing_type=sa.Text(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('audit_logs', 'entity_id',
               existing_type=sa.Text(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('audit_logs', 'action',
               existing_type=sa.Text(),
               type_=postgresql.ENUM('CREATE', 'UPDATE', 'DELETE', 'APPROVE', 'REVOKE', 'LOGIN', 'EMERGENCY', name='audit_action'),
               existing_nullable=False)
    op.alter_column('audit_logs', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('audit_logs', 'id',
               existing_type=sa.UUID(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.drop_column('audit_logs', 'entity')
    op.drop_column('audit_logs', 'actor')
    op.create_table('screens',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('device_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('resolution', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('orientation', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('screens_device_id_fkey')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('screens_tenant_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('screens_pkey'))
    )
    op.create_table('emergency_messages',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('severity', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('starts_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('ends_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='emergency_messages_created_by_fkey'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='emergency_messages_tenant_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='emergency_messages_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('locations',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('parent_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['locations.id'], name=op.f('locations_parent_id_fkey')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('locations_tenant_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('locations_pkey'))
    )
    op.create_table('schedules',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('zone_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('playlist_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('start_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('end_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlists.id'], name=op.f('schedules_playlist_id_fkey')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('schedules_tenant_id_fkey')),
    sa.ForeignKeyConstraint(['zone_id'], ['screen_zones.id'], name=op.f('schedules_zone_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('schedules_pkey'))
    )
    op.create_table('screen_layouts',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='screen_layouts_tenant_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='screen_layouts_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('emergency_media',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('emergency_message_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('media_asset_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['emergency_message_id'], ['emergency_messages.id'], name=op.f('emergency_media_emergency_message_id_fkey')),
    sa.ForeignKeyConstraint(['media_asset_id'], ['media_assets.id'], name=op.f('emergency_media_media_asset_id_fkey')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('emergency_media_tenant_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('emergency_media_pkey'))
    )
    op.create_table('screen_zones',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('layout_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('x', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('y', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('width', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('height', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['layout_id'], ['screen_layouts.id'], name=op.f('screen_zones_layout_id_fkey')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('screen_zones_tenant_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('screen_zones_pkey'))
    )
    op.create_table('playlists',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='playlists_tenant_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='playlists_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('content_versions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('media_asset_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('version_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('state', postgresql.ENUM('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'PUBLISHED', 'ARCHIVED', name='content_state'), server_default=sa.text("'DRAFT'::content_state"), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('approved_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='content_versions_created_by_fkey'),
    sa.ForeignKeyConstraint(['media_asset_id'], ['media_assets.id'], name='content_versions_media_asset_id_fkey'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='content_versions_tenant_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='content_versions_pkey'),
    sa.UniqueConstraint('media_asset_id', 'version_number', name='content_versions_media_asset_id_version_number_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_table('device_heartbeats',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('device_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('heartbeat_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('device_heartbeats_device_id_fkey')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('device_heartbeats_tenant_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('device_heartbeats_pkey'))
    )
    op.create_index(op.f('idx_heartbeat_device_time'), 'device_heartbeats', ['device_id', sa.literal_column('heartbeat_at DESC')], unique=False)
    op.create_table('playlist_items',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('playlist_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('content_version_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('position', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('duration_seconds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['content_version_id'], ['content_versions.id'], name=op.f('playlist_items_content_version_id_fkey')),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlists.id'], name=op.f('playlist_items_playlist_id_fkey')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('playlist_items_tenant_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('playlist_items_pkey'))
    )
    # ### end Alembic commands ###
